POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username" : "Muhammad Sheva2",
  "password" : "1234",
  "name" : "Saya Siapa2"
}

###

POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username" : "Muhammad Sheva2",
  "password" : "1234"
}

###

GET http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: eb1fa480-7917-402d-b157-a1ebfefa2363

###

PATCH http://localhost:3000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: eb1fa480-7917-402d-b157-a1ebfefa2363

{
  "name" : "Fahraj"
}

###

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291

###

POST http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: eb1fa480-7917-402d-b157-a1ebfefa2363

{
  "first_name" : "Joko",
  "last_name" : "Morro",
  "email" : "joko@pzn.com",
  "phone" : "324234234234"
}

###

GET http://localhost:3000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291

###

GET http://localhost:3000/api/contacts/317
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291

### Update

PUT http://localhost:3000/api/contacts/317
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291

{
  "first_name": "Rully",
  "last_name": "Nugraha",
  "email": "rully@pzn.com",
  "phone": "324234234234"
}

### Delete Contact

DELETE http://localhost:3000/api/contacts/317
Content-Type: application/json
Accept: application/json
Authorization: eb1fa480-7917-402d-b157-a1ebfefa2363

### Create Address

POST http://localhost:3000/api/contacts/316/addresses
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291

{
  "street" : "Kantor",
  "city" : "Jakarta",
  "province" : "DKI JAKARTA",
  "country" : "Indonesia",
  "postal_code" : "324234"
}


### List Addresses

GET http://localhost:3000/api/contacts/316/addresses
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291


### Get Address

GET http://localhost:3000/api/contacts/316/addresses/46
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291

### Update Address

PUT http://localhost:3000/api/contacts/316/addresses/46
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291

{
  "street" : "Kantor Bekerja",
  "city" : "Bekasi",
  "province" : "Jawa Barat",
  "country" : "Indonesia",
  "postal_code" : "324234"
}

### Remove Address

DELETE http://localhost:3000/api/contacts/316/addresses/46
Content-Type: application/json
Accept: application/json
Authorization: 19dfc22d-4545-45a9-9b36-ec0fc3fee291

### Membuat Resep Makanan

POST http://localhost:3000/api/ResepMakanan
Content-Type: application/json
Accept: application/json
Authorization: eb1fa480-7917-402d-b157-a1ebfefa2363

{
  "nama": "Goreng pisang2222",
  "bahan": "Bahan-Bahan pisang",
  "langkahpembuatan": "Langkah pembuatan"
}

### get Resep Makanan

GET http://localhost:3000/api/ResepMakanan/14
Content-Type: application/json
Accept: application/json
Authorization: eb1fa480-7917-402d-b157-a1ebfefa2363


### Update Resep Makanan

PUT http://localhost:3000/api/ResepMakanan/14
Content-Type: application/json
Accept: application/json
Authorization: eb1fa480-7917-402d-b157-a1ebfefa2363

{
  "nama": "Goreng Bakwan edit",
  "bahan": "Bahan-Bahan",
  "langkahpembuatan": "Langkah pembuatan"
}

### delete Resep Makanan

DELETE http://localhost:3000/api/ResepMakanan/14
Content-Type: application/json
Accept: application/json
Authorization: eb1fa480-7917-402d-b157-a1ebfefa2363

### Search Resep Makanan

GET http://localhost:3000/api/ResepMakanan?bahan=pisang
Content-Type: application/json
Accept: application/json
Authorization: eb1fa480-7917-402d-b157-a1ebfefa2363
